export enum ERRORS_ENUM {
  SIGN_IN_ERROR = "SIGN_IN_ERROR",
  SIGN_UP_ERROR = "SIGN_UP_ERROR",
  AUTHORIZATION_REQUIRED = "AUTHORIZATION_REQUIRED",
  ACCOUNT_DOES_NOT_EXIST_ERROR = "ACCOUNT_DOES_NOT_EXIST_ERROR",
  USER_AUTHORIZATION_ERROR = "USER_AUTHORIZATION_ERROR",
  API_SERVER_DOWN = "API_SERVER_DOWN",
  REQUIRED_PARAMS_ERROR = "REQUIRED_PARAMS_ERROR",
  GENERIC_ERROR = "GENERIC_ERROR",
  SESSION_EXPIRE_ERROR = "SESSION_EXPIRE_ERROR",
  NO_RECORDS_UPDATED = "NO_RECORDS_UPDATED",
}
